### ISSUE TITLE
666

### ISSUE THREAD

**Issue by adili001** [l15y/wenda#10]
怎么 联系你？

**Comment by l15y** [comment]
你有什么诉求

**Comment by adili001** [comment]
第一个问题：
第一次以下面的这种格式形成了100字左右的知识库，
问：什么是骨化性纤维瘤？
答：非骨化性纤维瘤是由组织成纤维细胞组成的干骺端错构瘤，又称干骺端纤维性缺损、非成骨性纤维瘤、组织细胞纤维瘤、干骺端错构瘤、纤维皮质缺损。把病灶小、无临床症状、病变局限于骨膜下或皮质内的称之为干骺端纤维性缺损或纤维皮质缺损，而把病灶较大，病变可扩展侵入髓腔而且常合并病理性骨折的称之为非骨化性纤维瘤或非成骨性纤维瘤，所以非骨化性纤维瘤和纤维皮质缺损是属非骨化性纤维瘤的两个病种或同一疾病中的两个不同表现。
但是打开chatPDF功能提问：什么是骨化性纤维瘤时，数据时加载了，但是提示未找到相关答案。

第二个问题：
第二次形成了800字左右的知识库，问相关的问题时，页面提示：发生错误，正在重新加载模型    后台显示错误 CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 6.00 GiB total capacity; 5.05 GiB already allocated; 0 bytes free; 5.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 6.00 GiB total capacity; 5.05 GiB already allocated; 0 bytes free; 5.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

是我的显存不够吗？我的显卡是GTX1660  而且数据也只是800字的数据

**Comment by l15y** [comment]
6个g的显存，确实少了点。可以考虑关闭多轮对话，每次提炼要点发问

**Comment by adili001** [comment]
好的，感谢

**Comment by adili001** [comment]
作者这个项目非常好，感谢

**Comment by adili001** [comment]
希望能够与你取得联系，能够第一时间获取项目的动态，然后尽我所能的帮到你。。

**Comment by l15y** [comment]
> 希望能够与你取得联系，能够第一时间获取项目的动态，然后尽我所能的帮到你。。

wx:cly0wx
