### ISSUE TITLE
建议将”知识库“按钮改为”本地知识库“和”联网“两个按钮，分别独立开关，共4种模式

### ISSUE THREAD

**Issue by fengtianyu88** [l15y/wenda#104]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
建议将”知识库“按钮改为”本地知识库“和”联网“两个按钮，分别独立开关，共4种模式

**Comment by fj198602** [comment]
运行llama，用英文提问，提示发生错误，正在重新加载模型。用中文提问，只回答2个字，但不会重载模型。

**Comment by alfgo** [comment]
这个建议听好了

**Comment by l15y** [comment]
先已实现通过auto独立查找
