### ISSUE TITLE
运行llama，用英文提问，提示发生错误，正在重新加载模型。用中文提问，只回答2个字，但不会重载模型。

### ISSUE THREAD

**Issue by fj198602** [l15y/wenda#105]
运行llama，用英文提问，提示发生错误，正在重新加载模型。用中文提问，只回答2个字，但不会重载模型。

**Comment by fj198602** [comment]
原来如此，多谢解惑

**Comment by liuyunrui123** [comment]
![image](https://user-images.githubusercontent.com/57593875/231435605-204c16d3-66ef-4239-8fa4-ac6ec9103338.png)
