### ISSUE TITLE
加载本地chatGLM6B 模型失败

### ISSUE THREAD

**Issue by readygo67** [l15y/wenda#107]
**Describe the bug**
从huggingface下载chatGLM模型到model/chatglm-6b中
![image](https://user-images.githubusercontent.com/78890754/231418273-ddd54fcc-edbf-4c0f-93e4-89421f6b59f7.png)

**To Reproduce**
bash run_GLM6b.sh

**Expected behavior**
正常执行

**Screenshots**
![image](https://user-images.githubusercontent.com/78890754/231421617-c61f3ea4-8200-4d00-a9aa-131f166a3c1b.png)

**Additional context**

**Comment by liuyunrui123** [comment]
我这测试正常跑，我是这样设置seetings.bat文件的：
```
set glm_path=model\chatglm-6b
set "glm_strategy=fp16i8 cuda"
```
显存不够大，我用了8位量化。

**Comment by readygo67** [comment]
我是在autoDL 上租的3090显卡跑的，setting.sh的内容如下
![image](https://user-images.githubusercontent.com/78890754/231450490-2c560c01-2a8e-4e5b-ba97-ba084e669661.png)

chatGLM-6B的版本是
![image](https://user-images.githubusercontent.com/78890754/231450904-1dbb4f34-050c-443d-9ac4-5706d0a7808c.png)

**Comment by readygo67** [comment]
这个问题的原因是autoDL 的服务器上却省没有安装git-lfs, 所以git clone https://huggingface.co/THUDM/chatglm-6b时其实是没有下载成功。 解决方法是1. 安装git-lfs,  2. 重新git clone https://huggingface.co/THUDM/chatglm-6b， 3. 检查shasum -a 256 ice_text.model。 可以参考：https://github.com/THUDM/ChatGLM-6B/issues/480
