### ISSUE TITLE
windows 11 下载的懒人版，运行chatglm6b.bat 报错，没有输出

### ISSUE THREAD

**Issue by niebaopeng** [l15y/wenda#109]
Symbol cudaLaunchKernel not found in C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\cudart64_65.dll
No compiled kernel found.
Compiling kernels : C:\Users\nieba\.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 C:\Users\nieba\.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\quantization_kernels_parallel.c -shared -o C:\Users\nieba\.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\quantization_kernels_parallel.so
'gcc' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Compile failed, using default cpu kernel code.
Compiling gcc -O3 -fPIC -std=c99 C:\Users\nieba\.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\quantization_kernels.c -shared -o C:\Users\nieba\.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\quantization_kernels.so
'gcc' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Kernels compiled : C:\Users\nieba\.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\quantization_kernels.so
Cannot load cpu kernel, don't use quantized model on cpu.
Using quantization cache
Applying quantization to glm layers

**Comment by l15y** [comment]
装cuda否

**Comment by sgb25sgb** [comment]
我也有同样的问题，Explicitly passing arevision' isencouragedWhenLoading a model with custom codeno malicious cotoensurede has been contributed in a newer revision.Explicitly passing a 'revision' is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.Explicitly passing a 'revision' is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.No compiled kernel found.Compiling kernels : C: Users 76002 .cache huaginaface modules transformers modules chatolm-6b-int4 guantization_kernels_parallel.cCompiling gcc -03 -fPIC -pthread -fopenmp -std=c99 C: Users(76002\.cache huggingfacemodules transformers_modulesichatolm-6b-int4 quantization kernels parallel.c -shared -0 C: Users 76002 .cache hugoinoface modulesitransformers_modules chatglm-6b-int4 quantization_kernels_parallel.soKernels compiled : C: Users 76002 .cache huggingface modules transformers-modules chatglm-6b-int4 quantization_kernels_parallel.so
Cannot load cpu kernel, don't use quantized model on cpu.Using quantization cacheApplying quantization to glm layers

**Comment by sgb25sgb** [comment]
但可以正常使用，搞不明白什么回事
