### ISSUE TITLE
知识库不准，用原标题提问，回答的完全不对，也不是原文内容

### ISSUE THREAD

**Issue by alexhmyang** [l15y/wenda#110]
![image](https://user-images.githubusercontent.com/10215059/231492853-f2f21380-bc90-4465-93a4-cbf304f9ebcd.png)

知识库不准，用原标题提问，回答的完全不对，也不是原文内容

这样的结果对吗？
知识库结果正确与否有什么评判标准吗？

**Comment by xs818818** [comment]
需要再等等，目前知识库效果还不够好，你可以先用bing

**Comment by alexhmyang** [comment]
> 需要再等等，目前知识库效果还不够好，你可以先用bing

有没有 类似 chatpdf的 私有化部署方案，没有的话 我们可以一起来研发呀

**Comment by ngbruce** [comment]
看控制台输出可以得知，搜索到的文本有时和问题的关联性不大，然后模型也不保证能按照代码里面的提示根据搜索文本回答，而是根据模型里固有的“思路”来回答。个人认为这种问题不是单单这个项目的路线能解决的，要从模型方面入手才行。

**Comment by l15y** [comment]
> > 需要再等等，目前知识库效果还不够好，你可以先用bing
> 
> 有没有 类似 chatpdf的 私有化部署方案，没有的话 我们可以一起来研发呀

欢迎参与知识库模组研发

**Comment by alexhmyang** [comment]
> > > 需要再等等，目前知识库效果还不够好，你可以先用bing
> > 
> > 
> > 有没有 类似 chatpdf的 私有化部署方案，没有的话 我们可以一起来研发呀
> 
> 欢迎参与知识库模组研发

怎么参与，留个 微信吧
