### ISSUE TITLE
删了 txt 里的内容，加入新文件，重新 运行 run_data_processing ，新文件没有加入索引，问答里搜不到该内容，删了 cache也不行

### ISSUE THREAD

**Issue by alexhmyang** [l15y/wenda#112]
删了 txt 里的内容，重新 运行 run_data_processing ，新文件没有加入索引，问答里搜不到该内容，删了 cache也不行

![image](https://user-images.githubusercontent.com/10215059/231506259-68d5cecf-060b-4492-9a6f-3f853b71bcd2.png)

**Comment by l15y** [comment]
环境，模式？

**Comment by alexhmyang** [comment]
> 环境，模式？

win11 , cuda11.7
直接双击 bat

**Comment by l15y** [comment]
模式？

**Comment by alexhmyang** [comment]
> 模式？

run_GLM6B.bat 
知识库模式 我也打开了

**Comment by l15y** [comment]
知识库模式是哪个

**Comment by alexhmyang** [comment]
> 知识库模式是哪个

直接双击 run_GLM6B.bat ，他就直接运行了，没有选 模式呀

**Comment by alexhmyang** [comment]
> 用最新的fess模式

windows懒人包里的 代码 更新了吗？还是 得 clone 最新代码 用 ubuntu跑，坑太多了

**Comment by l15y** [comment]
已更新
