### ISSUE TITLE
知识库加载失败： Index 'MAIN' does not exist in FileStorage('sy')

### ISSUE THREAD

**Issue by doxulovezh** [l15y/wenda#113]
知识库加载失败，请阅读说明：https://github.com/l15y/wenda Index 'MAIN' does not exist in FileStorage('sy')
 知识库加载完成 
warning: failed to mlock 159854592-byte buffer (after previously locking 0 bytes): Cannot allocate memory
Try increasing RLIMIT_MLOCK ('ulimit -l' as root).
...................................................................................................
.
llama_init_from_file: kv self size  = 6400.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 
 模型加载完成

**Comment by l15y** [comment]
所以你阅读了么
