### ISSUE TITLE
能否支持M1或M2的MAC下启动

### ISSUE THREAD

**Issue by lsmegranate** [l15y/wenda#121]
如题：

可否像ChatGLM-6B官方一样支持一下MAC下的显卡加载：
<img width="884" alt="image" src="https://user-images.githubusercontent.com/130434792/231856725-737cf7b9-34e7-4c8a-9721-be9ec9671f8d.png">

或者说可以在哪个设置里进行修改。

**Comment by l15y** [comment]
llm_glm6b.py

**Comment by lsmegranate** [comment]
感谢[l15y](https://github.com/l15y)大大的指点，已经顺利运行。这里把修改的部分贴出来，给有需要的小伙伴参考：

setting.sh中，增加Apple Silicon的gpu选项：

<img width="822" alt="image" src="https://user-images.githubusercontent.com/130434792/232136854-ad7c5d71-bfa6-4a9c-89b9-53d6a0160349.png">

llm_glm6b.py中，补上Apple Silicon的gpu设置：

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/130434792/232137116-c0885d12-ace2-4170-bc94-914e15d3cb19.png">

**Comment by l15y** [comment]
可以发个pr

**Comment by zhuozl** [comment]
新版反而不支持mps了。
