### ISSUE TITLE
刚了解到autogpt，wenda未来有这个方向吗？

### ISSUE THREAD

**Issue by shmily91** [l15y/wenda#124]
wenda能做到像autogpt那样吗？

**Comment by l15y** [comment]
开源模型目前泛华能力不足

**Comment by l15y** [comment]
其实很简单，直接在前端调我函数就能实现了
感兴趣可以试试

**Comment by shmily91** [comment]
> 其实很简单，直接在前端调我函数就能实现了 感兴趣可以试试

我要是有这能力我也想弄。可惜没这水平了，我在想这个那么火，要是你能在wenda做出来，估计你这个项目10w+star应该不成问题了吧

**Comment by l15y** [comment]
> 

新版本已经实现了自动化接口，目前完成了写论文的自动指令，各位可以自行开发其他功能的Auto，在\views\index.html里。建议参照写论文的例子

**Comment by shmily91** [comment]
> > 
> 
> 新版本已经实现了自动化接口，目前完成了写论文的自动指令，各位可以自行开发其他功能的Auto，在\views\index.html里。建议参照写论文的例子



看不太懂html，但是修改了长度和轮次限制。我不知道网页搜素是怎么提取信息的，我的想法是是能不能提取整个页面的文字，然后用glm对文本进行有用信息的提取，然后在进行回答的？总感觉页面提取出来的信息不太准确。你一句话让我通宵了哈哈哈

**Comment by l15y** [comment]
基于我目前提供的函数，你说这些功能都能实现
