### ISSUE TITLE
最新的懒人包是不是有错误？知识库用不了

### ISSUE THREAD

**Issue by shmily91** [l15y/wenda#125]
plugins的文件好像改了，但是相关的bat文件是不是没做调正 ，另外fess是不是还是用不了

**Comment by xufengnian** [comment]
类似，我这边的情况是知识库测试搜索关键字可以找到本地文档，勾选知识库按钮以后，提问就是不参考知识库，而且来源也是空

**Comment by l15y** [comment]
正确安装fess后可以用

**Comment by better319** [comment]
![Snipaste_2023-04-14_22-17-19](https://user-images.githubusercontent.com/13842581/232070030-2dc270fa-5a25-42e7-8f47-67b6de5964c1.png)
