### ISSUE TITLE
设置GPU的block

### ISSUE THREAD

**Issue by szj2ys** [l15y/wenda#127]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

我有两块GPU，默认的GPU已经占满了，怎么设置让wenda使用第二块呢，谢谢！

**Comment by diannaojiang** [comment]
在运行脚本里 python执行代码前设置环境变量   CUDA_VISIBLE_DEVICES
