### ISSUE TITLE
现在如何导入自己本地的知识库进去？

### ISSUE THREAD

**Issue by StarRanger** [l15y/wenda#133]
如何导入自己本地的知识库并且让知识在问答中生效？fess这种模式对测试来说还是太重了，有没有脚本可以后台直接导入的？

**Comment by l15y** [comment]
另外两个模式也重

**Comment by jessdy** [comment]
现在是否还支持s+x模式？或者fess模式？

**Comment by l15y** [comment]
都支持，但s x 模式需要自己把文件加回去
