### ISSUE TITLE
可否在回答中增加数据源的出处，类似于Bing这种，便于知识的回溯查找

### ISSUE THREAD

**Issue by lsmegranate** [l15y/wenda#147]
如下图：
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/130434792/232350864-5325d300-7d20-47ed-95b5-80e71fb33974.png">

**Comment by TheReluctantHeroes** [comment]
目前在答案底部已经实现显示来源了，在config.xml里把“知识库显示来源”设为True就行了。如果觉得纯文本显示比较丑陋，你可以参考比如 [https://twitter.com/GZhan5/status/1639488948195168256](https://twitter.com/GZhan5/status/1639488948195168256) 这样，按需美化网页界面

对于段落中精确标注引用出处的需求我表示怀疑，比起需求更像是炫技的伪需求。反正目前数据来源大概为了精确相关和资源考虑，也就五到十条左右，而且喂的自定义文章也不会很长，我不觉得回溯有什么不便。如果你要喂茫茫多的互联网信息并且需要细致的回溯和联想，为什么不直接用bingchat。

假如你真的很需要本地实现，开源的几个LLM模型大概没有这功能模板，可以考虑Fine-tune或者参考之前（已经被删除的）s或者x查找模式的思路，在获取完答案后针对来源和答案再作一次分词匹配或者语义检索。我还是那个观点，没必要过度设计，把生产力和硬件资源优先用在有意义的地方

**Comment by lsmegranate** [comment]
> 目前在答案底部已经实现显示来源了，在config.xml里把“知识库显示来源”设为True就行了。如果觉得纯文本显示比较丑陋，你可以参考比如 https://twitter.com/GZhan5/status/1639488948195168256 这样，按需美化网页界面
> 
> 对于段落中精确标注引用出处的需求我表示怀疑，比起需求更像是炫技的伪需求。反正目前数据来源大概为了精确相关和资源考虑，也就五到十条左右，而且喂的自定义文章也不会很长，我不觉得回溯有什么不便。如果你要喂茫茫多的互联网信息并且需要细致的回溯和联想，为什么不直接用bingchat。
> 
> 假如你真的很需要本地实现，开源的几个LLM模型大概没有这功能模板，可以考虑Fine-tune或者参考之前（已经被删除的）s或者x查找模式的思路，在获取完答案后针对来源和答案再作一次分词匹配或者语义检索。我还是那个观点，没必要过度设计，把生产力和硬件资源优先用在有意义的地方

非常感谢[TheReluctantHeroes](https://github.com/TheReluctantHeroes)大大的解答。

我描述一下我这边的应用场景，我觉得可能其他用户也会有类似需求。就是我的知识库可能是从爬虫抓取的，我并不知道抓取的完整内容，或者知识库是直接爬取的文件。当使用模型进行回答的时候，回答的某段可能会出现我感兴趣的内容，我想回溯一下看看更详细的原文，或者是原文中的图片或图表，如果有个数字标识符或者超链接直接打开是最好的。否则如果回复内容较多，我只能从引用的文档中挨个去找，有数字标识符或超链接就会方便很多。

**Comment by diannaojiang** [comment]
可能你可以在编写爬虫的时候就把标识符或者来源链接作为文件名，然后通过闻达Auto就可以实现对返回的文件名进行处理

**Comment by lsmegranate** [comment]
> 可能你可以在编写爬虫的时候就把标识符或者来源链接作为文件名，然后通过闻达Auto就可以实现对返回的文件名进行处理

谢谢，后面试试
