### ISSUE TITLE
建议加入对多显卡的支持

### ISSUE THREAD

**Issue by ChinaGPT** [l15y/wenda#16]
给公司做知识库的，建议能够对4个及以上的显卡做兼容，傻瓜式一键开启和配置。

**Comment by l15y** [comment]
我就一块显卡没法测试啊

**Comment by l15y** [comment]
1.像[diannaojiang](https://github.com/diannaojiang)说的，自己写个脚本 多个显卡分别用环境变量CUDA_VISIBLE_DEVICES=* 来指定 后台启动多个程序
2.不同实例采用不同端口运行
3.后面加个负载均衡
