### ISSUE TITLE
点清除历史后，刷新浏览器内容还在

### ISSUE THREAD

**Issue by 826568389** [l15y/wenda#162]
打开index.html
修改这个
							<v-list-item-title class="text-h6">
								闻达 Auto
								<v-btn color="#555" style="right: 1em;position: fixed;z-index: 1;" dark size="x-large"
									@click=**"clearhis"** :loading="loading">
									清除历史
								</v-btn>
							</v-list-item-title>
							
在	<script> 内增加这个方法
		clearhis=()=>{
			app.对话=[]
			window.localStorage.clear()
		}
				
解决刷新后浏览器缓存问题

**Comment by l15y** [comment]
中午就改了你不更新

**Comment by 826568389** [comment]
更新太快了。没来得及看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "l15y/wenda"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月19日(星期三) 下午5:11
***@***.***&gt;;
抄送:&nbsp;"xiao ***@***.******@***.***&gt;;
主题:&nbsp;Re: [l15y/wenda] 点清除历史后，刷新浏览器内容还在 (Issue #162)





 
中午就改了你不更新
