### ISSUE TITLE
unable to run buils_ST_data.bat

### ISSUE THREAD

**Issue by zxcvbn114514** [l15y/wenda#173]
**Describe the bug**
unable to run buils_ST_data.bat

**Additional context**
![image](https://user-images.githubusercontent.com/128148517/233759029-98763245-1c8b-41a7-a274-143e84c6708d.png)

**Comment by l15y** [comment]
文件没找到，要不运行目录不对，要不没这文件。建议直接双击运行

**Comment by zxcvbn114514** [comment]
> 文件没找到，要不运行目录不对，要不没这文件。建议直接双击运行

真的是双击运行啊大佬   :（ 我啥都没改

**Comment by l15y** [comment]
是用的git pull还是zip包？

**Comment by zxcvbn114514** [comment]
> 是用的git pull还是zip包？

github上下载的zip包，解压到本地运行

**Comment by l15y** [comment]
这是github的bug，直接pull
