### ISSUE TITLE
Fess搜索库的资料离奇丢失，需要再跑一遍Job Scheduler

### ISSUE THREAD

**Issue by huangzhongzhong** [l15y/wenda#174]
**Describe the bug**
fess的搜索库资料丢失，需要再跑一遍Job Scheduler 才正常。

**To Reproduce**
1我先是运行run_GLM6B.bat启动了闻达，运行正常。
![微信图片_20230422145801](https://user-images.githubusercontent.com/46183365/233768448-e299733c-b361-4766-939f-5788307993f0.png)

2.发现fess知识库未启动，去运行fess.bat，启动，试验了一下搜索正常。
![微信图片_20230422145809](https://user-images.githubusercontent.com/46183365/233768431-43aca068-37e1-4d7a-ba36-72416773923d.png)

3.重启闻达，发现知识库测试搜索不到鲁迅，再去知识库测试，发现无法搜索。
![e3dae27617d8b803ea8aa85fe21ced7](https://user-images.githubusercontent.com/46183365/233768458-4d3d66d6-29a0-4a5f-9db1-2f411f17a9c1.png)

4.再次运行原Job Scheduler任务后，发现能搜到部分了，但是文件很多，重新运行一次要好久。

**Expected behavior**
出现这种丢失问题时能快速恢复正常

**Desktop (please complete the following information):**
 - OS: win
 - Browser：Microsoft Edge
 - Version  版本 112.0.1722.48 (正式版本) (64 位)

**Comment by huangzhongzhong** [comment]
我的知识库是4.18G,看后台10G多了，这正常吗？
![image](https://user-images.githubusercontent.com/46183365/233768990-78e70500-a977-4d48-93a1-35ae013d9a28.png)

![image](https://user-images.githubusercontent.com/46183365/233769007-e888e89d-68ec-4613-b277-7f3eca4967e5.png)

**Comment by l15y** [comment]
与本项目无关
