### ISSUE TITLE
如何隐藏知识增强过程中搜集信息的过程,仅期望获得最终的答案?

### ISSUE THREAD

**Issue by shmily91** [l15y/wenda#176]
我希望在使用知识增强的过程中，想隐藏他搜集信息的过程，只希望他回答最终的问题，我能在哪里进行修改？

**Comment by l15y** [comment]
可以把显示的相关语句去掉
但是目前通过send方法的内容都会显示

**Comment by l15y** [comment]
好像确实有必要加这么个接口

**Comment by shmily91** [comment]
> 可以把显示的相关语句去掉 但是目前通过send方法的内容都会显示

我刚才试了一下，确实删除send依然会出现

**Comment by l15y** [comment]
已经加了，示例见sd的auto
