### ISSUE TITLE
如何写论文的功能，改成写其他文中的功能？

### ISSUE THREAD

**Issue by shmily91** [l15y/wenda#177]
我想把写论文的功能，改成写其他文种的功能，请问我该在哪里修改提纲。我找不到相关的代码，只看到罗马数字对应阿拉伯数字，我猜测修改或许从这里入手，但是我看了很多文件都找到相关的代码，请问我该怎么修改？

**Comment by l15y** [comment]
不是新传了一个根据提纲写的？

**Comment by shmily91** [comment]
谢谢，我把论文的功能复制到常用去，修改提示词发现可以了=
