### ISSUE TITLE
gen_data_st.py 近期更新后读取txt文档有问题

### ISSUE THREAD

**Issue by lsmegranate** [l15y/wenda#179]
如题：
<img width="1474" alt="image" src="https://user-images.githubusercontent.com/130434792/233800462-40c2f6f3-903d-44c6-8570-1743734e7670.png">

在执行第一步数据预处理时报错了，应该是对txt文档读取存在问题。我使用的txt文档都是转成了utf-8的，还是有这个问题。

**Comment by lsmegranate** [comment]
> 如题： <img alt="image" width="1474" src="https://user-images.githubusercontent.com/130434792/233800462-40c2f6f3-903d-44c6-8570-1743734e7670.png">
> 
> 在执行第一步数据预处理时报错了，应该是对txt文档读取存在问题。我使用的txt文档都是转成了utf-8的，还是有这个问题。

顺带说下，前两天的版本都是正常的，可以生成vectorstore_path 文件夹，后面更新后就出现这个报错了。

**Comment by yungangwu** [comment]
可能某个文件中有乱码，找到哪个文件，删了就行了

**Comment by eeric** [comment]
解决了吗？
能上传pdf格式吗？
