### ISSUE TITLE
用懒人包能启动，但一直加载模型失败

### ISSUE THREAD

**Issue by WilsonWu315** [l15y/wenda#18]
<img width="909" alt="image" src="https://user-images.githubusercontent.com/18652553/230317742-b964fa70-325f-43b0-af85-8c04f51ae3cf.png">
后台打印如下
127.0.0.1:who are you?
错误 Library cublasLt is not initialized Library cublasLt is not initialized

请问如何解决？

**Comment by adili001** [comment]
看看窗口的错误提示，还有可能是显存爆了的原因
