### ISSUE TITLE
用知识库写论文，最后会把来源放到问题中

### ISSUE THREAD

**Issue by hellodog667** [l15y/wenda#183]
测试了自动脚本写论文的功能，先列提纲，然后根据每一段提纲分别扩写，最后合并。不开知识库无问题，但开知识库（默认的bing），在扩写完所有提纲后，会开始扩写来源中的词语，例如知乎，QQ等。
![snipaste_20230423_210334](https://user-images.githubusercontent.com/46187175/233841441-a6631f4a-79bf-4a33-84da-e96314756616.jpg)

**Comment by l15y** [comment]
可以改auto或者关闭来源显示
