### ISSUE TITLE
在知识库，测试，好像只能显示10条？我想多显示一些怎么改？谢谢

### ISSUE THREAD

**Issue by scnc1987** [l15y/wenda#187]
在知识库，测试，好像只能显示10条？我想多显示一些怎么改？谢谢
我已经在 config.xml 里面把“知识库抽取数量”改成20了，点测试但还是只显示5条。

**Comment by l15y** [comment]
改错地方了

**Comment by scnc1987** [comment]
> 改错地方了

那改哪里？谢谢
