### ISSUE TITLE
【feat request】如何知道AI搜索的内容和结果？

### ISSUE THREAD

**Issue by yhyu13** [l15y/wenda#190]
有办法像new bing那样，展示搜索的关键字和内容？我开启了bing模式，但是没有办法弄清楚，模型是否在使用联网搜索？

**Comment by yhyu13** [comment]
![截屏2023-04-25 17 36 10](https://user-images.githubusercontent.com/19365678/234237081-19898299-2795-44c7-a442-d809864571e4.png)

饿，好像都显示在终端里了，能搬运到网页里面去吗

**Comment by l15y** [comment]
方法1在配置中打开开源
方法2用auto查询
