### ISSUE TITLE
可以提供mac版的吗？

### ISSUE THREAD

**Issue by SAKURA-LBY** [l15y/wenda#192]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yhyu13** [comment]
https://github.com/l15y/wenda/issues/121 chatglm没合并。

**Comment by l15y** [comment]
没给我发pr。可以照着改一下

> #121 chatglm没合并。 chatglm Mac上速度极慢
> 
> llama.cpp需要手动编译一下python binding 同时还要安装pytorch nightly build
> 
> 目前mac下部署还是有些麻烦的 @l15y
