### ISSUE TITLE
【st知识库】把txt folder里面的文件删除，同事把txt-out 里面的文件删除（包括checkpoint）,重新配置知识库，不生效，还是会读取之前的文件

### ISSUE THREAD

**Issue by wayne0627** [l15y/wenda#193]
- ![image](https://user-images.githubusercontent.com/50519623/234492711-14ebda2c-71e1-42cd-8683-2b34148757bf.png)
- ![image](https://user-images.githubusercontent.com/50519623/234492745-ff0bd24c-0fa2-459a-afe3-bdb2856e26ae.png)
- 重启服务器也不行

**Comment by lsmegranate** [comment]
索引读取的是vectorstore_path文件夹里的东西，所以知识库如果有新内容加入，需要重新启动一次gen_data_st.py，来生成新的索引

**Comment by wayne0627** [comment]
非常感谢，重启服务器，问题解决
