### ISSUE TITLE
修改了fess的查询方式

### ISSUE THREAD

**Issue by bobo04020802** [l15y/wenda#194]
大神您好：
目前zhishiku_fess.py的find采用去除stopwords之后再进行知识库查询
但是存在一个问题就是可能输入内容过多，知识库无法匹配到内容（fess本身的查询机制吧）
此处我在您去除stopwords的时候，方法体里加了一个分割，再进行分批次提交给fess查询，最后追加到一个list中，再根据_id去重。
我目前的使用中能满足要求。

如果觉得对您有用，可以追加到新版本中~~

**Comment by l15y** [comment]
挺好，发pr吧
