### ISSUE TITLE
Linux单独部署的问题

### ISSUE THREAD

**Issue by zw81929** [l15y/wenda#197]
1、config.xml在部署chatglm-6b的时候，默认config.xml存在问题，model/chatglm-6b-int4 应该和实际相匹配，不算太大问题
2、requirements 没有 torch包
3、部署过程感觉云里雾里，现在新版（4.22）到底支持哪些？ rwkv支持不支持
4、st模式，text2vec-large-chinese 一直报错 No sentence-transformers model found with name model/text2vec-large-chinese
     但是确实是解压缩了，如何配置？
5、Linux版本建议还是修改下部署说明吧，现在感觉整个文档有点乱

**Comment by zw81929** [comment]
启动后，页面回复永远是 ...... ，后台报错也看不到，有点郁闷了

**Comment by l15y** [comment]
没时间写。你有时间可以写
1至4都不是问题
