### ISSUE TITLE
能部署API吗？

### ISSUE THREAD

**Issue by eeric** [l15y/wenda#198]
wenda.py怎么修改成使用API？

**Comment by l15y** [comment]
参考https://github.com/AlanLee1996/wenda-webui

**Comment by eeric** [comment]
wenda-webui具体怎么用，能做个API使用说明吗？

**Comment by eeric** [comment]
修改：
uvicorn.run(app, host='127.0.0.1', port=8100, workers=1)
这样可以运行了

**Comment by gg22mm** [comment]
workers大于1就不行了，为什么

**Comment by zdh6090** [comment]
可以运行，但是不能post调用啊
