### ISSUE TITLE
[help] 运行“运行GLM6B.bat”报错

### ISSUE THREAD

**Issue by zx2021** [l15y/wenda#2]
windows10
cuda12
pytorch2.0.0
python3.10
已下载[simcse-chinese-roberta-wwm-ext并放在sentence-transformers\simcse-chinese-roberta-wwm-ext。并完整安装requirements.txt
修改了GLM6BAPI.py的138行model_path="D:/chatglm-6B-int4"（chatglm的绝对路径）
修改了model_name = "D:/Python/Python310/Lib/site-packages/sentence_transformers/simcse-chinese-roberta-wwm-ext"（simcse-chinese-roberta-wwm-ext的绝对路径）
运行“PS D:\Desktop\wenda-main> .\运行GLM6B.bat”
报错
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "D:\Desktop\wenda-main\GLM6BAPI.py", line 162, in <module>
    vectorstore = FAISS.load_local('xw', embeddings=embeddings)
  File "D:\Python\Python310\lib\site-packages\langchain\vectorstores\faiss.py", line 406, in load_local
    index = faiss.read_index(str(path / "index.faiss"))
  File "D:\Python\Python310\lib\site-packages\faiss\swigfaiss.py", line 9651, in read_index
    return _swigfaiss.read_index(*args)
RuntimeError: Error in __cdecl faiss::FileIOReader::FileIOReader(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:68: Error: 'f' failed: could not open xw\index.faiss for reading: No such file or directory
No compiled kernel found.
Compiling kernels : C:\Users\zx\.cache\huggingface\modules\transformers_modules\local\quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 C:\Users\zx\.cache\huggingface\modules\transformers_modules\local\quantization_kernels_parallel.c -shared -o C:\Users\zx\.cache\huggingface\modules\transformers_modules\local\quantization_kernels_parallel.so
'gcc' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Compile failed, using default cpu kernel code.
Compiling gcc -O3 -fPIC -std=c99 C:\Users\zx\.cache\huggingface\modules\transformers_modules\local\quantization_kernels.c -shared -o C:\Users\zx\.cache\huggingface\modules\transformers_modules\local\quantization_kernels.so
Kernels compiled : C:\Users\zx\.cache\huggingface\modules\transformers_modules\local\quantization_kernels.so
Cannot load cpu kernel, don't use quantized model on cpu.
Using quantization cache
Applying quantization to glm layers
Exception ignored in: <module 'threading' from 'D:\\Python\\Python310\\lib\\threading.py'>
Traceback (most recent call last):
  File "D:\Python\Python310\lib\threading.py", line 1567, in _shutdown
    lock.acquire()
KeyboardInterrupt:

**Comment by l15y** [comment]
错的应该是这句话。vectorstore = FAISS.load_local('xw', embeddings=embeddings)
在这里面我读取了xw这个文件夹。这个文件夹在项目里是没有的，它是数据生成gendata.py里面。生成的你所需要查找的文档的向量。因为我的数据是从互联网上爬去的新闻可能会有一些问题。我没有承认了，你可以把自己的txt格式的文件放在名为txt的文件夹里。然后运行这个叫做数据预处理的批处理。是我的说明没有写清楚，今天晚上的时候我给他加上。

**Comment by cymx333** [comment]
transformers应该用哪个版本合适？我这儿报错
ModuleNotFoundError: No module named 'transformers_modules.model/chatglm-6b-int4'

**Comment by cymx333** [comment]
> 

改了绝对路径之后跑通了。 
另外，我想问一下，gcc编译器是必须安装的吗，是不是程序没有调用GPU，而是用的CPU跑的？ 请大佬不吝赐教。@l15y

**Comment by cymx333** [comment]
根据观察，在预处理过程中使用的是CPU，使用过程中调用GPU。另外想请教一下大佬，预处理能否调用GPU，CPU处理起来速度极慢。

**Comment by l15y** [comment]
gcc不用装
预处理，转化句向量的模型默认gpu计算，想用cpu需要改langchain源码
