### ISSUE TITLE
今天发现 bing索引是否有问题? 

### ISSUE THREAD

**Issue by samni728** [l15y/wenda#204]
之前测试配置了bing为知识库,一直都正常 git pull后发现这个情况
可以索引测试 可是在问答里 打开知识库 不引用内容,是什么原因? 另外 索引测试时 2字词组正常 4字词组会不显示.例如 女性美妆 测试没有内容 ,而美妆 则可以,是不是有bug了 之前没有这个问题!
![iShot2023-04-28 01 02 05](https://user-images.githubusercontent.com/68144774/234936410-2d45b747-cfbe-447d-ba46-d6aced17e208.jpg)
![iShot2023-04-28 01 01 52](https://user-images.githubusercontent.com/68144774/234936441-256611d5-1871-47e6-bfcb-a556a32211c1.jpg)
![iShot2023-04-28 00 58 36](https://user-images.githubusercontent.com/68144774/234936474-f6a81cf5-ab40-4bba-8222-91806c7a6d11.jpg)
![iShot2023-04-28 00 55 58](https://user-images.githubusercontent.com/68144774/234936486-28d59b9b-cee8-4292-b009-b3ce33fdd268.jpg)
![iShot2023-04-28 00 55 45](https://user-images.githubusercontent.com/68144774/234936498-9f09597a-48b2-4fdf-b196-1d93e49e8d6d.jpg)
![iShot2023-04-28 00 55 36](https://user-images.githubusercontent.com/68144774/234936502-fb6c3f47-96fb-430c-9fec-8de48fba8cc3.jpg)
可是使用 广州的天气 又是可以的引用知识库的 这是什么原因呢
![iShot2023-04-28 01 05 11](https://user-images.githubusercontent.com/68144774/234937474-76f2cb80-41b1-4f43-b901-ceeeba0f052c.jpg)

**Comment by loche666** [comment]
我用mix模式构建知识库，bing检索也是时好时坏，不知道什么原因，但感觉像是ip被限制请求了~

**Comment by l15y** [comment]
今天bing不好用。你直接去网页搜也这样

**Comment by zhuyunqi1990** [comment]
我也是这样，今天只能搜短词短语，不能搜长句子
