### ISSUE TITLE
st知识库分割错误

### ISSUE THREAD

**Issue by huashiyiqike** [l15y/wenda#205]
**Describe the bug**
有的txt无法正确建立索引。
附件两txt中，刑法能正确索引，但是红楼梦不行

相关配置
```

  <Library>
        <property>
            <name>Type</name>
            <value>st</value>
            <description>知识库类型:
                bing → cn.bing搜索，仅国内可用
                fess → fess搜索引擎
                mix → 知识库融合,需设置参数
                st → sentence_transformers,内测版本
                kg → 知识图谱,暂未启用
            </description>
        </property>
        <property>
            <name>Show_Soucre</name>
            <value>True</value>
            <description>知识库显示来源</description>
        </property>
        <property>
            <name>Size</name>
            <value>200</value>
            <description>知识库最大长度</description>
        </property>
        <property>
            <name>Step</name>
            <value>2</value>
            <description>知识库默认上下文步长</description>
        </property>


 <ST>
            <property>
                <name>Path</name>
                <value>txt</value>
                <description>知识库文本路径</description>
            </property>
            <property>
                <name>Size</name>
                <value>20</value>
                <description>分块大小</description>
            </property>
            <property>
                <name>Overlap</name>
                <value>0</value>
                <description>分块重叠长度</description>
            </property>
            <property>
                <name>Count</name>
                <value>3</value>
                <description>知识库抽取数量</description>
            </property>
            <property>
                <name>Model_Path</name>
                <value>/home/lqwsl/python/text-generation-webui/models/GanymedeNil_text2vec-large-chinese</value>
                <description>向量模型存储路径</description>
            </property>
            <property>
                <name>Device</name>
                <value>cuda</value>
                <description>sentence_transformers运行设备:cpu、cuda。仅用于查找，索引强制使用cuda</description>
            </property>
        </ST>
```

**Screenshots**
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/5295447/235044190-78597dc6-caf8-44c6-be0a-13c7221601ad.png">

<img width="871" alt="image" src="https://user-images.githubusercontent.com/5295447/235044201-0482554e-8f94-4f14-8996-2eae4be0cc4a.png">

**Additional context**
[刑法.txt](https://github.com/l15y/wenda/files/11349436/default.txt)
[红楼梦.txt](https://github.com/l15y/wenda/files/11349433/default.txt)

**Comment by l15y** [comment]
显示你文件有乱码

**Comment by huashiyiqike** [comment]
@l15y 
第一次编辑了好久没发成功，第二次写的不够详细。。

那个乱码截屏是vectorstore_path\index.pkl文件，可以看到刑法部分是有正常建立索引，但是红楼梦部分都是在一起了，没有by chunk 分割

**Comment by l15y** [comment]
看看红楼梦的句号是不是正常的句号

**Comment by huashiyiqike** [comment]
和刑法一样的。

刑法开头一大段也是没能正确分割，后面换行多的ddou都是正常

[红楼梦.txt](https://github.com/l15y/wenda/files/11351702/default.txt)
[刑法.txt](https://github.com/l15y/wenda/files/11351705/default.txt)

**Comment by l15y** [comment]
我这边正常，啥都没改

按语：�h}�hhsuh��(hh�h}�ub�$f96242d2-6ada-4a15-ab75-d338c0c548d2�h
)��}�(h
}�(h�c拙著《红楼梦全解本》出版后，受到了不少专家与读者的好评，甚为欣慰。�h}�hhsuh��(hh�h}�ub�$b30088fe-6253-450d-b3c2-1487bcca2b07�h
)��}�(h
}�(h��但也有读者认为，如果能删掉部分注文，既不影响读者阅读，也可节省书的成本，使更多读者买得起。�h}�hhsuh��(hh�h}�ub�$6721aefa-c38a-4336-8638-7eed47f210c6�h
)��}�(h
}�(h��恰好中央编译出版社准备出版四大古典小说套书，为了平衡四部小说的注文，《红楼梦》的注文也嫌太长。�h}�hhsuh��(hh�h}�ub�$eb929741-4888-4cd1-a1b1-16ad6d7c7d9a�h
)��}�(h
}�(h��因此接受读者的建议，将《红楼梦全解本》的注文删掉了差不多一半，其他一概未动；换言之，此版《红楼梦》校注本，实即《红楼梦全解本》的删节本（仅删注文）。�h}�hhsuh��(hh�h}�ub�$8ffede8a-4cd7-4d52-bfac-b09e01d360dc�h
)��}�(h
}�(h�]因此《校注前言》仍用《红楼梦全解本》的《校注前言》，不再另写。�h}�hhsuh��(hh�h}�ub�$feb44d17-aea7-46a4-9525-6113cdbfcd1c�h
)��}�(h
}�(h��《红楼梦》以其包罗万象的内容，博大精深的思想，精湛完美的艺术，丰富生动的语言，尤其是众多栩栩如生的人物形象，不仅在中国小说史上奇峰独秀，而且在世界文学之林独树一帜。�h}�hhsuh��(hh�h}�ub�$3084b9cf-1f65-4167-8c94-b5917f91ac94�h
)��}�(h
}�(h�K它是我国文化遗产中的珍品，值得每一个中国人所珍视。�h}�hhsuh��(hh�h}�ub�$494c9b8f-c240-4349-98db-21c3392aae4e�h
)��}�(h
}�(h�u《红楼梦》在其尚未完稿的时候，已经被人竞相传抄，辗转传阅，不胫而走，蜚声神州。�h}�hhsuh��(hh�h}�ub�$bb63fbed-26f7-4555-9d69-18445f8d8165�h
)��}�(h
}�(h��不仅“士大夫几乎家有《红楼梦》一书”（清·潘炤《从心录》卷首），而且“家弦户诵，妇孺皆知”（清·缪艮《文章游戏初编》卷六）。�h}�hhsuh��(hh�h}�ub�$9d17b90e-91c6-4bf2-a620-04d830be50fc�h
)��}�(h
}�(h��上层社会更出现了“开谈不说《红楼梦》，读尽诗书也枉然”（清·得舆《京都竹枝词·时尚门》）的时尚。�h}�hhsuh��(hh�h}�ub�$13770473-f23a-44c5-91ef-f429b2f7a572�h
)��}�(h
}�(h��《红楼梦》的魅力也使其商业价值大增，“好事者每传抄一部，置庙市中，昂其值，得数十金，可谓不胫而走者矣”（清·程伟元《〈红楼梦〉序》）。�h}�hhsuh��(hh�h}�ub�$b289ad50-87d9-497a-8e6b-6712c56f51f7�h
)��}�(h
}�(h��至高鹗续写后四十回、由程伟元以活字正式出版完整的一百二十回本后，更出现了风行全国的盛况。�h}�hhsuh��(hh�h}�ub�$a01974d9-7af5-40a8-9a4b-ac015cd73cde�h
)��}�(h
}�(h��时至今日，即使读不懂《红楼梦》的人，也都看过《红楼梦》电影或电视剧，对《红楼梦》的故事和人物无不耳熟能详。�h}�hhsuh��(hh�h}�ub�$f126f86d-7c5f-43ef-8f2a-f844dd1b984e�h
)��}�(h
}�(h�W因此《红楼梦》已经不是普通的小说，而成为全民珍视的国宝了。�h}�hhsuh��(hh�h}�ub�$b7cd7f91-b519-4f32-9204-4942a9026382�h
)��}�(h
}�(h�x中国古代的文人墨客、传统学者、官僚士夫，无不鄙薄小说，最多被视为茶余饭后的谈资。�h}�hhsuh��(hh�h}�ub�$fd41728d-605a-4288-b201-611440a990b5�h
)��}�(h
