### ISSUE TITLE
出现有关<frozen importlib._bootstrap>警告

### ISSUE THREAD

**Issue by zhuyunqi1990** [l15y/wenda#208]
更新了新的wenda以后，重新填写了config就发现，先是无法读取模型，在反复修改和尝试重装整个虚拟环境以后，现在模型加载成功以后依然有如下警告，尤其是有关frozen importlib._bootstrap重复出现，这个模块究竟影响到了社么功能，因为现在对话是没有问题。
(chatglm) G:\wenda>python wenda.py
Namespace(Config='config.xml', Port=None, Logging=None, LLM_Type=None)

    Logging: False
    Port: 5001
    LLM_Type: glm6b
    Path: model/chatglm-6b
    Strategy: cuda fp16
    Lora: null
    library:
        Type: bing
        Show_Soucre: True
        Size: 200
        Step: 2
        bing:
            Count: 7
            Academic: False
            Searc_Site: cn.bing.com
<frozen importlib._bootstrap>:914: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
知识库加载完成
<frozen importlib._bootstrap>:914: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py:1227: DeprecationWarning: invalid escape sequence '\?'
  ["\?", "？"],
serving on 0.0.0.0:5001 view at http://127.0.0.1:5001
<frozen importlib._bootstrap>:914: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
Loading checkpoint shards:  12%|███████▏                                                 | 1/8 [00:02<00:15,  2.Loading checkpoint shards:  25%|██████████████▎                                          | 2/8 [00:04<00:Loading checkpoint shards:  38%|█████████████████████▍                                   | 3/8 [00Loading checkpoint shards:  50%|████████████████████████████▌                            | Loading checkpoint shards:  62%|███████████████████████████████████▋                Loading checkpoint shards:  75%|██████████████████████████████████████████▊  Loading checkpoint shards:  88%|████████████████████████████████████████████Loading checkpoint shards: 100%|████████████████████████████████████████████Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 8/8 [00:14<00:00,  1.79s/it]
模型加载完成

**Comment by l15y** [comment]
没事
