### ISSUE TITLE
问一下chatgpt的api在哪里输入？run_openaiapi.bat里面我改了发现没反应

### ISSUE THREAD

**Issue by mayichen1987** [l15y/wenda#210]
发生错误，正在重新加载模型No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://onboard.openai.com for details, or email support@openai.com if you have any questions.

**Comment by l15y** [comment]
`rem set OPENAI_API_KEY=123`
前面的rem要删了

**Comment by mayichen1987** [comment]
> `rem set OPENAI_API_KEY=123` 前面的rem要删了

谢谢，那代理要在哪里设置，还是得系统全局代理？

**Comment by l15y** [comment]
llm_openai.py:`    openai.api_base = "https://gpt.lucent.blog/v1"`

**Comment by mayichen1987** [comment]
> llm_openai.py:` openai.api_base = "https://gpt.lucent.blog/v1"`

谢谢，不过我要问的是类似于 127.0.0.1:7680 这样的代理要写在哪里？也是是写在llm_openai.py里面吗？因为API应该不能在大陆直接调用

**Comment by l15y** [comment]
要用全局代理

**Comment by mayichen1987** [comment]
> 要用全局代理

懂了谢谢
