### ISSUE TITLE
你好，想问一下关于config.xml，能否提供更详细的配置说明，例如该项配置作用在哪里，是否必须，各种不同配置有何差异，非常感谢！

### ISSUE THREAD

**Issue by wangchenQQ** [l15y/wenda#212]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by l15y** [comment]
短期内，计划把有限的精力放在功能完善上。哪里不懂可以直接问

**Comment by wangchenQQ** [comment]
感谢感谢，我现在遇到了这样的问题，我就是用普通的服务器，遇到了下面的问题，请帮忙看看
操作系统：Ubuntu 20.04.5 LTS
物理cpu：2
Namespace(Config='config.xml', LLM_Type=None, Logging=None, Port=None)

    Logging: true
    Port: 17860
    LLM_Type: glm6b
    Path: model/chatglm-6b-int4
    Strategy: cpu fp16i4
    Lora: null
    library: 
        Type: st
        Show_Soucre: Ture
        Size: 200
        Step: 2
        st: 
            Path: txt
            Size: 20
            Overlap: 0
            Count: 5
            Model_Path: model/text2vec-large-chinese
            Device: cpu
serving on 0.0.0.0:17860 view at http://127.0.0.1:17860
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
/home/msyd/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/modeling_chatglm.py:1260: DeprecationWarning: invalid escape sequence \?
  ["\?", "？"],
No sentence-transformers model found with name model/text2vec-large-chinese. Creating a new one with MEAN pooling.
No compiled kernel found.
Compiling kernels : /home/msyd/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 /home/msyd/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/quantization_kernels_parallel.c -shared -o /home/msyd/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/quantization_kernels_parallel.so
Exception: Error in faiss::FileIOReader::FileIOReader(const char*) at /project/faiss/faiss/impl/io.cpp:67: Error: 'f' failed: could not open vectorstore_path/index.faiss for reading: No such file or directory
vectorstore加载失败，请先构建索引
知识库加载完成
Load kernel : /home/msyd/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/quantization_kernels_parallel.so
Setting CPU quantization kernel threads to 2
Parallel kernel is not recommended when parallel num < 4.
Cannot load cpu kernel, don't use quantized model on cpu.
Using quantization cache
Applying quantization to glm layers
Killed

**Comment by wangchenQQ** [comment]
这是我的相关配置
<property>
   <name>LLM_Type</name>
   <value>glm6b</value>
   <description>LLM模型类型:glm6b、rwkv、llama、chatglm</description>
</property>
 <GLM6B>
            <property>
                <name>Path</name>
                <value>model/chatglm-6b-int4</value>
                <description>glm模型位置</description>
            </property>
            <property>
                <name>Strategy</name>
                <value>cpu fp16i4</value>
                <description>glm 模型参数  支持：
                    "cpu fp16i4" fp16原生模型要 自行量化为int4跑在cpu上可以使用这个参数
                </description>
            </property>

<Library>
        <property>
            <name>Type</name>
            <value>st</value>
            <description></description>
        </property>

<ST>
  <property>
    <name>Device</name>
    <value>cpu</value>
    <description>sentence_transformers运行设备:cpu、cuda。仅用于查找，索引强制使用cuda</description>
  </property>

**Comment by l15y** [comment]
要先构建索引。应该已经给你弹出文档相应位置了，看一下
