### ISSUE TITLE
知识库的两种模式是如何切换的

### ISSUE THREAD

**Issue by RipperTs** [l15y/wenda#213]
在`常见问题`里面发现这段话：
> 闻达的这个知识库实际上是属于搜索类的吗？
答：是用两种方法在知识库里搜一个大概的文本再把问题和参考数据一起给模型让模型回答整理，分为索引和语义分析两种。

想了解下是如何切换索引还是语义的呢？

**Comment by l15y** [comment]
fess-索引
st-语义
建议提问前阅读文档
