### ISSUE TITLE
启用知识库后问答无法进行

### ISSUE THREAD

**Issue by SQMHZ** [l15y/wenda#239]
5.5懒人包
测试可以：
![1](https://user-images.githubusercontent.com/54303773/236456390-76b54f6b-84ae-4694-865e-cf354ea77d42.png)

不启用知识库时问答正常，但启用知识库后发送问题只会回答省略号：
![2](https://user-images.githubusercontent.com/54303773/236456961-6b518cb2-72f1-4457-8b49-9ce9dca54e72.png)

**Comment by l15y** [comment]
已经修了
