### ISSUE TITLE
推荐一下rwkv.cpp

### ISSUE THREAD

**Issue by Asukaleo-aa** [l15y/wenda#242]
[rwkv.cpp](https://github.com/saharNooby/rwkv.cpp)这个项目是将rwkv的模型转换成[ggml](https://github.com/ggerganov/ggml)，极大地提高了rwkv模型在纯cpu环境下的运行效率，目前rwkv在更新模型的时候也有提供转换好的版本，非常推荐引入一下这个模型

**Comment by tpoisonooo** [comment]
啊俺作为白嫖党，主要看 精度-速度 情况。  wenda/README.md 里说 rwkv 比较慢，除非 rwkv 精度明显高才有吸引力。

**Comment by l15y** [comment]
显存足够的情况下，rwkv是快于glm的。不过感觉已经有cuda了，用cpp意义不大

**Comment by Asukaleo-aa** [comment]
> 显存足够的情况下，rwkv是快于glm的。不过感觉已经有cuda了，用CPP意义不大

主要是有些朋友没有N卡只能用cpu，用这个cpp的版本效率还是挺快的，14B的运行速度显著高于原版3B模型的运行速度

**Comment by tpoisonooo** [comment]
确实，穷苦院校 GPU 配置堪忧。

**Comment by diannaojiang** [comment]
https://github.com/l15y/wenda/commit/ee9e6c43889d69ad4011ead7f1784f1b59d36ef7

**Comment by l15y** [comment]
已实现
