### ISSUE TITLE
 import torch出错

### ISSUE THREAD

**Issue by bigmarten** [l15y/wenda#246]
**Describe the bug**
安装了cuda11.8，更新.bat -> 运行.bat 后出现如下错误。

**To Reproduce**
Traceback (most recent call last):
  File "D:\develop\workspace\AI\wd-git\wenda\wenda.py", line 3, in <module>
    import torch
  File "D:\develop\anaconda3\Lib\site-packages\torch\__init__.py", line 445, in <module>
    raise ImportError(textwrap.dedent('''
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.

**Comment by l15y** [comment]
要装，而且不能直接通过pip，要去官网找命令
