### ISSUE TITLE
【FR】在使用过程中切换需要调用的知识库

### ISSUE THREAD

**Issue by wwjCMP** [l15y/wenda#250]
本地具有多个知识库，但是回答只是调用默认的default库，还有本地库没有的内容希望只用网络搜索的内容来回答。
回答的质量很大程度上取决于输入给模型的数据，由于检索得到的数据并不总是匹配的，导致回答质量参差不齐。
其中最中主要的问题就是知识的混用，不同知识的语句中包含类似语义的字句，导致都会被提问检索到，这样就很容易答非所问。
还有对于本地库没有的知识，同时将本地库检索到的内容混进去就会降低回答的质量。
所以希望可以实现本地各个库都可以被调用，并且在使用的过程中可以选择开关。

**Comment by diannaojiang** [comment]
各个库的混用mix就可以  使用过程中选择的话可以考虑下用auto怎么实现

**Comment by l15y** [comment]
已实现，见前端`find_dynamic`函数。例程见`闻达笔记`auto
