### ISSUE TITLE
网页搜索可以增加duckduckgo吗

### ISSUE THREAD

**Issue by jarheadjoe** [l15y/wenda#257]
用起来比bing稳定，不需要自己正则清洗。调用duckduckgo_search库即可
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/21330284/236756100-40462ab0-c0e1-4d8a-a3d8-a2f0c11c3788.png">
这个搜索方式在https://github.com/yanqiangmiffy/Chinese-LangChain项目中被使用。
如果可行，我这边在plugins中增加下，然后pr？

**Comment by l15y** [comment]
可以，可惜我连不上
