### ISSUE TITLE
linux-3090使用glm-gpu模型问题

### ISSUE THREAD

**Issue by zck573693104** [l15y/wenda#26]
1.glm60B已经在3090跑起来可以用了
2.在wenda里面也进行了路径替换
3.创建了txt目录，输了多行数据
4.执行脚本适合报错如下
5.求救作者我是哪里出问题了
glm模型地址 /home/hycan/HDD1/opt/zck/nlp/ChatGLM-6B/model
rwkv模型地址 model/RWKV-4-Raven-7B-v7-ChnEng-20230404-ctx2048.pth
rwkv模型参数 cuda fp16i8 *18+
日志记录 True
chunk_size 200
chunk_count 1
Traceback (most recent call last):
  File "GLM6BAPI.py", line 140, in <module>
    import zhishiku
  File "/home/hycan/HDD1/opt/zck/nlp/wenda/zhishiku.py", line 5, in <module>
    ix = storage.open_index()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/whoosh/filedb/filestore.py", line 176, in open_index
    return indexclass(self, schema=schema, indexname=indexname)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/whoosh/index.py", line 421, in __init__
    TOC.read(self.storage, self.indexname, schema=self._schema)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/whoosh/index.py", line 618, in read
    raise EmptyIndexError("Index %r does not exist in %r"
whoosh.index.EmptyIndexError: Index 'MAIN' does not exist in FileStorage('sy')
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:08<00:00,  1.06s/it]
模型加载完成

**Comment by zck573693104** [comment]
这个  没有被执行到 python gen_data.py

**Comment by Give-me-yasoo** [comment]
额~ 原文档没有把顺序写明白。
你应该先执行对应的run_data_processon 文件，构建好知识库，生成sy目录，然后whoosh才可以进行全文索引

**Comment by zck573693104** [comment]
对TXT文档有什么要求嘛？我看直接read然后add进去了，看来是整篇文章作为了输入，但是使用发现，回答问题时候，容易出现迷糊。

**Comment by zck573693104** [comment]
运行起来还是很顺利的，谢谢作者
