### ISSUE TITLE
知识库多轮问答问题

### ISSUE THREAD

**Issue by daydayup-zyn** [l15y/wenda#264]
我预购建了txt语料，在进行知识库rtst模式的多轮问答时，“他目前的工作岗位是什么”，明明可以识别出问题的意图，但是查询不到预购建的信息，必须要将“他”指代的人名写清楚才可以，建议优化一下
![微信图片_20230510134501](https://github.com/l15y/wenda/assets/61485340/284bb5ca-26d5-4118-afe1-1195c1a90fb8)
![image](https://github.com/l15y/wenda/assets/61485340/d413362c-4306-41c1-a0ad-9c545312559d)

**Comment by l15y** [comment]
这是llm的问题
