### ISSUE TITLE
Chatglm 6B 8bit 模型 运行报错 

### ISSUE THREAD

**Issue by axonaxis** [l15y/wenda#267]
**Describe the bug**
在运行Chatglm 6B 4bit时正常，但是运行chatglm 6B 8bit及非量化版本时报错，运行报错,显示发生错误，正在重新加载模型name 'model' is not defined,

运行python wenda.py -t glm6b命令后

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [chrome]
 - Version [22.04]

![QQ截图20230510182223](https://github.com/l15y/wenda/assets/30280846/35ed28b7-5b3b-4551-adb7-607334b47f45)
![QQ截图20230510183351](https://github.com/l15y/wenda/assets/30280846/ae10ae61-d690-464a-b13b-5a71ad146526)

**Comment by l15y** [comment]
感觉不是wenda的问题，去glm问问
