### ISSUE TITLE
发生错误，正在重新加载模型name 'model' is not defined

### ISSUE THREAD

**Issue by XFZJ2022** [l15y/wenda#268]
<img width="991" alt="image" src="https://github.com/l15y/wenda/assets/99186870/901da835-7ecc-4cc5-bd57-f197161233e7">

5-10的懒人包，网盘下载的模型，确认model下面放了模型。

<img width="340" alt="image" src="https://github.com/l15y/wenda/assets/99186870/8d95669e-f512-4faf-bad2-24a912841cd1">

3070显卡的电脑报错哦。请教大神。

**Comment by l15y** [comment]
模型没下好
