### ISSUE TITLE
局域网使用 “当前连接不安全，无法访问媒体” 无法使用语音输入、人脸识别

### ISSUE THREAD

**Issue by lhtpluto** [l15y/wenda#274]
**Describe the bug**
局域网使用 “当前连接不安全，无法访问媒体” 无法使用语音输入、人脸识别

**To Reproduce**
1. Go to '打开首页提示 “当前连接不安全，无法访问媒体” '
2. Click on '人脸识别'或Click on '语音输入'
3. 无反应

**Desktop (please complete the following information):**
 - OS: WIN11
 - Browser edge

**Comment by lhtpluto** [comment]
只能在本机使用语音输入、人脸识别，通过局域网打开网页后不能使用语音输入、人脸识别

**Comment by l15y** [comment]
浏览器限制
可以用tls

**Comment by lhtpluto** [comment]
> 浏览器限制 可以用tls
求指点在程序里怎么修改，让页面启用TLS

在浏览器里把安全改到低，以及添加受信任站点，都继续反馈“当前连接不安全，无法访问媒体”

**Comment by l15y** [comment]
只是有这个提示，不影响功能
```
if (navigator != null && (window.location.toString().toUpperCase().indexOf("HTTPS") > -1 || window.location.toString().toUpperCase().indexOf("127") > -1)) {

} else {
    alert("当前连接不安全，无法访问媒体")
}
```

**Comment by lhtpluto** [comment]
拿笔记本1、笔记本2、台式机分别测试，局域网使用 无法使用语音输入、人脸识别

在笔记本1上部署，笔记本1本机可以使用语音输入、人脸识别，但笔记本2通过局域网访问笔记本1，无法使用语音输入、人脸识别

**Comment by cat88hzh** [comment]
我看到这个判断在wenda-autos-face-recognition.js 中，可以去掉
