### ISSUE TITLE
4月5日，仅chatGLM，知识库为sentence-transformers方式 发生错误，正在重新加载模型

### ISSUE THREAD

**Issue by ZengWenJian123** [l15y/wenda#28]
4月5日，仅chatGLM，知识库为sentence-transformers方式 出现错误
报错如下，发生错误，正在重新加载模型
![image](https://user-images.githubusercontent.com/32101524/230570955-ebbd4983-efc3-4f81-931c-6b26f33230ed.png)

lm模型地址 model\chatglm-6b-int4
embeddings模型地址 model\simcse-chinese-roberta-wwm-ext
vectorstore保存地址 xw
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
D:\zwj\AI\wenda\45sentence-transformers\WPy64-31090\python-3.10.9.amd64\lib\site-packages\langchain\chains\conversational_retrieval\base.py:191: UserWarning: `ChatVectorDBChain` is deprecated - please use `from langchain.chains import ConversationalRetrievalChain`
  warnings.warn(
<frozen importlib._bootstrap>:914: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
serving on http://127.0.0.1:17860
Symbol cudaLaunchKernel not found in C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\cudart64_65.dll
No compiled kernel found.
Compiling kernels : C:\Users\zwj\.cache\huggingface\modules\transformers_modules\local\quantization_kernels_parallel.c
Compiling gcc -O3 -pthread -fopenmp -std=c99 C:\Users\zwj\.cache\huggingface\modules\transformers_modules\local\quantization_kernels_parallel.c -shared -o C:\Users\zwj\.cache\huggingface\modules\transformers_modules\local\quantization_kernels_parallel.so
'gcc' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Compile failed, using default cpu kernel code.
Compiling gcc -O3 -fPIC -std=c99 C:\Users\zwj\.cache\huggingface\modules\transformers_modules\local\quantization_kernels.c -shared -o C:\Users\zwj\.cache\huggingface\modules\transformers_modules\local\quantization_kernels.so
Kernels compiled : C:\Users\zwj\.cache\huggingface\modules\transformers_modules\local\quantization_kernels.so
Cannot load cpu kernel, don't use quantized model on cpu.
Using quantization cache
Applying quantization to glm layers
127.0.0.1:你好
错误 Library cublasLt is not initialized Library cublasLt is not initialized
glm模型地址 model\chatglm-6b-int4
embeddings模型地址 model\simcse-chinese-roberta-wwm-ext
vectorstore保存地址 xw
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.

**Comment by l15y** [comment]
Library cublasLt is not initialized ，看看是不是环境没装好

**Comment by FelisDwan** [comment]
我是之前为了nuitka下了gcc+mingw64的包：https://winlibs.com，后来一直没用成功就没管，这次用闻达提示这个gcc问题找了一下才发现我环境没设置😂照着这个https://blog.csdn.net/qq_36292543/article/details/121145239把mingw改成mingw64设置好了系统环境路径以后就不提示gcc问题了

**Comment by ZengWenJian123** [comment]
后面我自己调整了一下，其实是懒人包里面chatGLM模型出现了问题，可以从其他地址下载模型之后，修改setting.bat 的set glm_path路径即可。

**Comment by l15y** [comment]
> 后面我自己调整了一下，其实是懒人包里面chatGLM模型出现了问题，可以从其他地址下载模型之后，修改setting.bat 的set glm_path路径即可。

还是cuda环境的问题。可能换了路径环境好了
