### ISSUE TITLE
知识库调用

### ISSUE THREAD

**Issue by Maomaoxion** [l15y/wenda#286]
![image](https://github.com/l15y/wenda/assets/81891401/cdd71994-ac83-4652-a914-8cc61a28ea1f)
![image](https://github.com/l15y/wenda/assets/81891401/8fa2c619-fd21-4316-b2cd-4cfc3083bcac)

调用知识库接口，提交后报错500，提交失败，多点几次又成功提交了？？？

**Comment by l15y** [comment]
bing被墙了，新版已经增加相应错误处理
