### ISSUE TITLE
想要加载ChatGLM-6B应该怎么做？

### ISSUE THREAD

**Issue by Datou** [l15y/wenda#32]
不是int4的模型，是FP16（无量化）的那个模型。

**Comment by l15y** [comment]
1.下载模型
2.在seetting里把模型路径指向新模型

**Comment by Datou** [comment]
![image](https://user-images.githubusercontent.com/15013/230700548-fb7c2fb8-b19a-431e-9da1-9014c50cb9be.png)

我放好了模型，修改了settings.bat
set glm_path=model\chatglm-6b
rem glm模型位置

运行run_GLM6B.bat，cmd窗口不断的显示“系统找不到指定的路径。”
![image](https://user-images.githubusercontent.com/15013/230700670-10b4bece-5dac-4cbf-ae75-4ae13263d5d1.png)

**Comment by l15y** [comment]
把echo off关了，看看啥没找到

**Comment by l15y** [comment]
如果不是懒人包，要自己写下Python路径
