### ISSUE TITLE
希望增加对返回代码的缩进的显示以及高亮提示

### ISSUE THREAD

**Issue by jcs130** [l15y/wenda#37]
前端显示的代码没有缩进以及高亮
<img width="1878" alt="a781fc136815668a66bbd244b8d41cf" src="https://user-images.githubusercontent.com/4521497/230726573-d818df2e-a26c-49c9-9504-adac078b76e4.png">

但是看后端输出的其实是有的：
<img width="876" alt="e841ed8586246012a3a6a4550329e58" src="https://user-images.githubusercontent.com/4521497/230726631-b7595a8c-8188-4a01-bd68-495b1a781c24.png">

**Comment by l15y** [comment]
已完成
