### ISSUE TITLE
有没有考虑视频教程鸭

### ISSUE THREAD

**Issue by ding567** [l15y/wenda#4]
有没有考虑一下做个视频教程鸭，对我这种小白也友好还能顺带宣传🥰

**Comment by l15y** [comment]
暂时没有精力。如果有人想做视频，新版懒人包，都欢迎，请和我联系，我会把相关链接加到readme里

**Comment by TheReluctantHeroes** [comment]
- [闻达-懒人包-安装使用教程](https://www.bilibili.com/video/BV1aX4y1z7ar/)
- [开源模型chatGLM整合包闻达一键部署初体验|叫板文心一言](https://www.bilibili.com/video/BV1kv4y1J75i/)
- [开源GPT加上自己的知识库比ChatGTP更精准更专业](https://www.bilibili.com/video/BV19o4y1J7mL/)

**Comment by ding567** [comment]
谢谢！


---原始邮件---
发件人: &quot;Ghost in the ***@***.***&gt;
发送时间: 2023年4月17日(周一) 中午1:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [l15y/wenda] 有没有考虑视频教程鸭 (Issue #4)




  
闻达-懒人包-安装使用教程
 
开源模型chatGLM整合包闻达一键部署初体验|叫板文心一言
 
开源GPT加上自己的知识库比ChatGTP更精准更专业
  
&mdash;
