### ISSUE TITLE
每次都重启模型？？

### ISSUE THREAD

**Issue by ZnOKelvin** [l15y/wenda#44]
127.0.0.1:你好
错误 'ChatGLMForConditionalGeneration' object has no attribute 'stream_chat' 'ChatGLMForConditionalGeneration' object has no attribute 'stream_chat'
glm模型地址 C:\ChatGLM_SERVER\model\chatglm-6b
embeddings模型地址 model\simcse-chinese-roberta-wwm-ext
vectorstore保存地址 xw
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards:  12%|███████▏                                                 | 1/8 [00:01<00:08,  1.26s/it]D:\AI_GLM\Wenda02\WPy64-31090\python-3.10.9.amd64\lib\site-packages\langchain\chains\conversational_retrieval\base.py:191: UserWarning: `ChatVectorDBChain` is deprecated - please use `from langchain.chains import ConversationalRetrievalChain`
  warnings.warn(
<frozen importlib._bootstrap>:914: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
serving on http://127.0.0.1:17860
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 8/8 [00:09<00:00,  1.19s/it]

**Comment by l15y** [comment]
先更新

**Comment by l15y** [comment]
你的chatglm-6b版本太旧，不支持流式
