### ISSUE TITLE
模型加载问题

### ISSUE THREAD

**Issue by guyuexia** [l15y/wenda#49]
我使用的是[ChatGLM-6B]的官方模型，因为是6G显卡，所以加载模型的时候是通过修改参数（quantize(4)）让6G显卡跑起来的。
请问一下这个项目应该在哪里修改模型参数？
或者官方量化后的4-bit模型在哪里下载？我一直没找到。
先谢谢了

**Comment by l15y** [comment]
\plugins\llm_glm6b.py
https://huggingface.co/THUDM/chatglm-6b-int4
