### ISSUE TITLE
设置 chunk_size 数值没有效果

### ISSUE THREAD

**Issue by ngbruce** [l15y/wenda#54]
**Describe the bug**
设置 chunk_size 数值没有效果

修改 settings.bat 当中的参数 set chunk_size=200 到更高的数值，实际运行时，观察控制台输出的参考文本(红色)，其截取的长度比修改前没有变化，长度都是约1000字节上下，大概300个中文字左右。
**To Reproduce**
修改 settings.bat 当中的参数 set chunk_size=   到不同的数值可以复现此问题，例如 400, 800，2000 等。

**Comment by l15y** [comment]
你的知识库模式？x模式是否重新生成索引？

**Comment by TheReluctantHeroes** [comment]
看代码可知：

对于x模式，chunk_size仅在建立索引时在CharacterTextSplitter函数中被调用，然后存入settings.vectorstore_path实现持久化，而不是在加载zhishiku时被调用，所以你必须先重建索引，不然光改这个数值不会生效的

对于s模式，settings.chunk_size仅在加载zhishiku时在find函数中被调用。不过s模式重新生成索引时似乎不会删原来已有，如果你是通过修改txt数据文件方式作观察测试，也会有影响，可以手动删掉整个sy目录再重建

**Comment by ngbruce** [comment]
> 你的知识库模式？x模式是否重新生成索引？

你好，我在s模式下使用。
x模式我现在还没调通，不知道为何在运行gen data时，在输出“开始读取数据”后一直卡住不动又没有报错。

**Comment by ngbruce** [comment]
> 看代码可知：
> 
> 对于x模式，chunk_size仅在建立索引时在CharacterTextSplitter函数中被调用，然后存入settings.vectorstore_path实现持久化，而不是在加载zhishiku时被调用，所以你必须先重建索引，不然光改这个数值不会生效的
> 
> 对于s模式，settings.chunk_size仅在加载zhishiku时在find函数中被调用。不过s模式重新生成索引时似乎不会删原来已有，如果你是通过修改txt数据文件方式作观察测试，也会有影响，可以手动删掉整个sy目录再重建

我在s模式下使用，修改这个参数后，我都会删除sy目录重新跑一次 run data processing的，但没有效果。

**Comment by ngbruce** [comment]
补充一下，我的 Python 版本 3.10.8,  PyTroch 版本  1.13.0+cu117 ，不知道和大家的是否一样

**Comment by l15y** [comment]
s模式，因为库，一个文件有多段匹配会返回多个，中间用……连接。每段长度为chunk_size
