### ISSUE TITLE
使用自定义语料库报错

### ISSUE THREAD

**Issue by LifeNT** [l15y/wenda#57]
[Document(page_content='药品注册管理办法\n\n（2020年1月22日国家市场监督管理总局令第27号公布 自2020年7月1日起施行）\n\n第一章 总 则', metadata={'source': 'txt_out\\药品注册管理办法2020.txt'}), Document(page_content='第一百零九条 国家药品监督管理局依法向社会公布药品注册审批事项清单及法律依据、审批要求和办理时限，向申请人公开药品注册进度，向社会公开批准上市药品的审评结论和依据以及监督检查发现的违法违规行为，接受社会监督。\n\n批准上市药品的说明书应当向社会公开并及时更新。其中，疫苗还应当公开标签内容并及时更新。', metadata={'source': 'txt_out\\药品注册管理办法2020.txt'}), Document(page_content='申 请人取得药品注册证书后，为药品上市许可持有人（以下简称持有人）。\n\n第四条 药品注册按照中药、化学药和生物制品等进行分类 注册管理。\n\n中药注册按照中药创新药、中药改良型新药、古代经典名方中药复方制剂、同名同方药等进行分类。\n\n化学药注册按照化学药创新药、化学药改良型新药、仿制药等进行分类。\n\n生物制品注册按照生物制品创新药、生物制品改良型新药、已上市生物制品（含生物类似药）等进行分类。', metadata={'source': 'txt_out\\药品注册管理办法2020.txt'})]
127.0.0.1:system:结合以下文段, 用中文回答用户问题。如果无法从中得到答案，忽略文段内容并用中文回答用户问题。

药品注册管理办法
（2020年1月22日国家市场监督管理总局令第27号公布 自2020年7月1日起施行）
第一章 总 则
---
第一百零九条 国家药品监督管理局依法向社会公布药品注册审批事项清单及法律依据、审批要求和办理时限，向申请人公开药品注册进 度，向社会公开批准上市药品的审评结论和依据以及监督检查发现的违法违规行为，接受社会监督。
批准上市药品的说明书应当向社会公开并及时更新。其中，疫苗还应当公开标签内容并及时更新。
---
申请人取得药品注册证书后，为药品上市许可持有人（以下简称持有人）。
第四条 药品注册按照中药、化学药和生物制品等进行分类注册管理。
中药注册按照中药创新药、中药改良型新药、古代经典名方中药复方制剂、同名同方药等进行分类。
化学药注册按照化学药创新药、化学药改良型新药、仿制药等进行分类。
生物制品注册按照生物制品创新药、生物制品改良型新药、已上市生物制品（含生物类似药）等进行分类。

user:最新药品注册管理办法发布日期

错误 local variable 'ctx' referenced before assignment local variable 'ctx' referenced before assignment
附件是我导入的语料：

[药品注册管理办法2020.txt](https://github.com/l15y/wenda/files/11185729/2020.txt)

**Comment by LifeNT** [comment]
补充一下，我使用的设置：

set llm_type=rwkv
set zsk_type=x

**Comment by l15y** [comment]
这是bug，刚刚已经更新
