### ISSUE TITLE
自定义语料库出现死循环

### ISSUE THREAD

**Issue by LifeNT** [l15y/wenda#60]
我检查了一下，txt_out 下面只有一个文件，但你看截图，出现有三个同名文件，我确实训练过几次，难道在哪里记录了每次的训练结果？

提问后，它开始无限重复回答相同内容，然后我中断了。

![QQ截图20230410001238](https://user-images.githubusercontent.com/7828213/230783975-5a259263-0d81-4736-884f-6cf10cd947f8.png)

**Comment by TheReluctantHeroes** [comment]
按照目前gen_data_s.py的逻辑，确实是你每训练一次，哪怕txt目录内容完全相同，也会额外保存一份新的索引到sy目录下。然后在你提问时，zhishiku_s.py会查询sy目录下所有的索引，因为你执行了三次run_data_processing，于是就看到了”三个一样的文件“。解决方法是把sy目录整个删掉，然后重建索引，就只有一份了

至于回答时的鬼打墙，那大概是另一个问题

**Comment by LifeNT** [comment]
谢谢提醒，晚上试试，无限重复的问题，貌似和模型有关，我测试了14B，7B，3B各个模型，最终发现，只有14B不会无限重复，其它两个都会重复，但这个可能也跟索引重复有关？

**Comment by l15y** [comment]
top_p调到0.8可以有效改进
