### ISSUE TITLE
懒人包默认配置，8GB 3070下爆显存

### ISSUE THREAD

**Issue by skmc1976** [l15y/wenda#68]
这里要在哪儿修改配置，才能解决这个问题呢？

**Comment by l15y** [comment]
应该不会爆。具体情况？

**Comment by TheReluctantHeroes** [comment]
是搜索外部资料里提到的关键词时爆显存，还是加载模型后就爆？取消勾选”知识库“按钮试试呢？

**Comment by skmc1976** [comment]
> 应该不会爆。具体情况？

抱歉，发现我朋友修改了指定的模型，改为默认模型的int4就没问题了。感谢！

**Comment by skmc1976** [comment]
> 是搜索外部资料里提到的关键词时爆显存，还是加载模型后就爆？取消勾选”知识库“按钮试试呢？
> 
> 如果是自己额外下的RWKV-4-Raven-7B-v7-ChnEng-20230404-ctx2048爆显存，改用chatglm-6b-int4

您说的对，确实是指定了别的模型导致的，加载时候就爆显存了，我的问题。感谢！
