### ISSUE TITLE
QA机器人如何加入QA的语料成为知识库，有这方面的规划还是大致想法实现的嘛？

### ISSUE THREAD

**Issue by zck573693104** [l15y/wenda#71]
QA机器人如何加入QA的语料成为知识库，有这方面的规划还是大致想法实现的嘛？
我将A当做知识加进去了，效果不是太好，容易理解多了。还是加入QA比较好点。

**Comment by TheReluctantHeroes** [comment]
参考隔壁的建议 [https://github.com/imClumsyPanda/langchain-ChatGLM/issues/13#issuecomment-1495243514](https://github.com/imClumsyPanda/langchain-ChatGLM/issues/13#issuecomment-1495243514)

第一行Q
第二行A

这么准备语料（接近fine tune模型的数据集格式）。然后用x模式，走sentence transformer做语义搜索，再优化一下prompt的指令模板

**Comment by zck573693104** [comment]
> 

按照每个文件
第一行Q
第二行A
准备了三个文件的语料，但是输入问题1时候，会把其他文件的Q也会同时回答出来

**Comment by david5515** [comment]
> 

我这边也遇到了同样的问题，有解决方案么？

**Comment by diannaojiang** [comment]
设置Count为1就只会返回最相近的一条答案了，然后目前你可以每个问答放到一个txt中 用fess进行索引
