### ISSUE TITLE
什么时候支持Vicuna

### ISSUE THREAD

**Issue by jingslunt** [l15y/wenda#72]
```
https://github.com/lm-sys/FastChat

**Comment by stevezhang88** [comment]
同问。vicuna很重要。

**Comment by l15y** [comment]
这个我显存跑不起啊。支持中文么？

**Comment by dongqf123** [comment]
> 

可以搞一个量化版的，13B-4bit 可以在一般的cpu上运行，我的cpu能够在4 token/sec。球球您考虑一下vicuna叭

**Comment by jingslunt** [comment]
> 这个我显存跑不起啊。支持中文么？

也是支持cpu的，当然支持中文
体验地址
https://chat.lmsys.org/

**Comment by dongqf123** [comment]
> 
应该是这个
https://huggingface.co/eachadea/ggml-vicuna-13b-4bit/tree/main

**Comment by jcs130** [comment]
是不是可以直接下这个 https://huggingface.co/eachadea/vicuna-13b 然后通过参数 改 int8 还是 int4

**Comment by l15y** [comment]
完成，已经更新。明天再整理下

**Comment by liuyunrui123** [comment]
> 

不是兄弟，你测试过这个模型效果吗，这个cpu运行的，我这跑起来测试效果非常差，中文回复不完整，很多时候还不对题

**Comment by dongqf123** [comment]
> > 
> 
> https://huggingface.co/eachadea/ggml-vicuna-13b-4bit/tree/main 不是兄弟，你测试过这个模型效果吗，这个cpu运行的，我这跑起来测试效果非常差，中文回复不完整，很多时候还不对题
> 
> 我觉得直接用下面这个会更好： https://huggingface.co/anon8231489123/vicuna-13b-GPTQ-4bit-128g

GPTQ好像只支持GPU，因为我的是AMD的所以我没用。中午呢差是因为它都是用英文语料训练的，但是你的知识库里面正好需要一个英文模型。求大佬可以兼容CPU的那个模型，我感觉很多人都是AMD或者没有独显

**Comment by dongqf123** [comment]
> 

下面的那个确实会更好，但是好像不支持AMD显卡...

**Comment by liuyunrui123** [comment]
> > > 
> > 
> > 
> > https://huggingface.co/eachadea/ggml-vicuna-13b-4bit/tree/main 不是兄弟，你测试过这个模型效果吗，这个cpu运行的，我这跑起来测试效果非常差，中文回复不完整，很多时候还不对题
> > 我觉得直接用下面这个会更好： https://huggingface.co/anon8231489123/vicuna-13b-GPTQ-4bit-128g
> 
> GPTQ好像只支持GPU，因为我的是AMD的所以我没用。中午呢差是因为它都是用英文语料训练的，但是你的知识库里面正好需要一个英文模型。求大佬可以兼容CPU的那个模型，我感觉很多人都是AMD或者没有独显
----------------------------------------------------------
就我测试效果来看，这个cpu跑出来的结果，有和没有没差别，完全不能用，满口胡话。

**Comment by liuyunrui123** [comment]
难道是我的i5 12400 cpu太差了，英文提问直接重启加载模型，中文就蹦几个字胡话
![image](https://user-images.githubusercontent.com/57593875/231435605-204c16d3-66ef-4239-8fa4-ac6ec9103338.png)

**Comment by l15y** [comment]
我也发现效果挺差。Python实现中文还有bug。GPTQ那个有事例项目么

**Comment by dongqf123** [comment]
> 我也发现效果挺差。Python实现中文还有bug。GPTQ那个有事例项目么

https://github.com/qwopqwop200/GPTQ-for-LLaMa

**Comment by dongqf123** [comment]
我是用https://github.com/mps256/vicuna.ps1 自动部署的ggml-vicuna-13b-4bit.bin 效果很好啊，不知道为什么你们都觉得效果差。不过还是求大佬能支持cpu部署vicuna

**Comment by liuyunrui123** [comment]
> 我也发现效果挺差。Python实现中文还有bug。GPTQ那个有事例项目么

GPTQ 那个我也试过了，效果略好些，但感觉还是不如cahtglm，而且有个严重问题，会生成自问自答内容，暂时不知道咋解

**Comment by dongqf123** [comment]
> cpu的已经支持了

大佬，懒人包里的vicuna模型有两个压缩包，为什么第二个压缩包解压不了呢？第一个压缩包解压后指定模型后只要随便发一句话就“发生错误，正在重新加载模型”。

**Comment by l15y** [comment]
> > cpu的已经支持了
> 
> 大佬，懒人包里的vicuna模型有两个压缩包，为什么第二个压缩包解压不了呢？第一个压缩包解压后指定模型后只要随便发一句话就“发生错误，正在重新加载模型”。

两个压缩包是一个
具体报错？
