### ISSUE TITLE
懒人包应用报错

### ISSUE THREAD

**Issue by yangzijiang98** [l15y/wenda#73]
每次提问后都会报
<img width="950" alt="image" src="https://user-images.githubusercontent.com/102526523/230850130-7d6e04e9-51a7-40ba-8450-7976108bb684.png">

<img width="549" alt="image" src="https://user-images.githubusercontent.com/102526523/230849939-279c4a58-a43b-48b8-b876-33b0a586f0e7.png">
然后就开始重新加载模型，但是加载完提问还是这个报错

**Comment by l15y** [comment]
安装cuda了么

**Comment by l15y** [comment]
提示cpmkernal未安装

**Comment by CCTVastu** [comment]
我检查了懒人包里有cpmkernal，且用requestment又安装了一遍还是出现上述报错
