### ISSUE TITLE
建议问答记录添加一键清空功能

### ISSUE THREAD

**Issue by fengtianyu88** [l15y/wenda#74]
**Is your feature request related to a problem? Please describe.**
问答多次之后历史记录很长，无法快速一键清空。

**Describe the solution you'd like**
问答记录添加一键清空功能。
可添加类似ChatGPT的多卡片聊天记录。

**Comment by TheReluctantHeroes** [comment]
![屏幕截图 2023-04-10 175347](https://user-images.githubusercontent.com/1256317/230879103-073d5a64-0347-48d7-8a5b-c8842dbff346.png)
鼠标移动到右上角的这个清空按钮试过了吗？

**Comment by fengtianyu88** [comment]
感谢，找到啦~
