### ISSUE TITLE
run_rwkv总是报ModuleNotFoundError: No module named 'rwkv',但是我已经安装了

### ISSUE THREAD

**Issue by minguo** [l15y/wenda#76]
下载了rwkv模型，settings已经设置好路径，运行run_rwkv.bat，报ModuleNotFoundError: No module named 'rwkv'

但是我已经重新在自带的WPy64-38100\python-3.8.10.amd64环境下安装了rwkv库，
运行python -m rwkv也可以正常提示有rwkv库，但是运行run_rwkv.bat就是报错没有rwkv库，

我下的是最新的版本，求助

**Comment by l15y** [comment]
新版懒人包已经内置了rwkv库，看是不是用错环境了

**Comment by TheReluctantHeroes** [comment]
首先确保settings.bat的编码没问题，我记得今天 @l15y 有个更新后，settings.bat变成了GB2312
如果编码不是utf-8，就重新存为utf-8
然后检查settings.bat中的前两行python解释器路径是不是自己目录下那一份库

或者直接修改 run_rwkv.bat，在 %PYTHON% xxx.py 前加一行：
`pip install rwkv`
或者
`pip install rwkv -i https://pypi.tuna.tsinghua.edu.cn/simple/`
运行安装一次大概就可以，随便它装到哪个python环境去

**Comment by l15y** [comment]
> 首先确保settings.bat的编码没问题，我记得今天 @l15y 有个更新后，settings.bat变成了GB2312 也许会造成某些路径字符失效，不确定。若编码不是utf-8，先用gb2312打开并重新另存为utf-8

GB2312是我专门改的，不然utf8的bom被去掉，会被win识别为GB2312造成乱码

**Comment by minguo** [comment]
> 

谢谢，可以鸟，我单独运行包里的环境安装居然不行，得在bat里安装一次，难道是我对python环境的理解有什么问题吗？
