### ISSUE TITLE
4.10最新版：知识库由bing搜索实现:运行run_data_processing.bat，提示错误

### ISSUE THREAD

**Issue by 1353604736** [l15y/wenda#77]
F:\ChatGPT\GPT\wenda\\WPy64-38100\python-3.8.10.amd64\python.exe: can't open file 'plugins/gen_data_bing.py': [Errno 2] No such file or directory
请按任意键继续. . .

**Comment by TheReluctantHeroes** [comment]
这个模式不需要运行run_data_processing.bat吧
