### ISSUE TITLE
这一句报错，因为huggingface没登录，怎么改成本地已经下载的呀

### ISSUE THREAD

**Issue by ding567** [l15y/wenda#8]
embeddings = HuggingFaceEmbeddings(model_name=model_name)
这一句报错，因为huggingface没登录，怎么改成本地已经下载的呀

发生异常: RepositoryNotFoundError
401 Client Error. (Request ID: Root=1-642c3974-240560a346fb2eb565ed790b)

Repository Not Found for url: https://huggingface.co/api/models/sentence-transformers/text2vec-base-chinese.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/sentence-transformers/text2vec-base-chinese

The above exception was the direct cause of the following exception:

  File "E:\AI模型\wenda-main\GLM6BAPI.py", line 152, in <module>
    embeddings = HuggingFaceEmbeddings(model_name=model_name)
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-642c3974-240560a346fb2eb565ed790b)

Repository Not Found for url: https://huggingface.co/api/models/sentence-transformers/text2vec-base-chinese.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

**Comment by l15y** [comment]
https://github.com/l15y/wenda#chatpdf%E5%8A%9F%E8%83%BD%E5%9C%A8chatglm-6b%E6%A8%A1%E5%9E%8B%E5%AE%9E%E7%8E%B0

**Comment by Vebrun** [comment]
?? 为什么这个链接没什么用就关闭了
