### ISSUE TITLE
建议后续增加接入Stable Diffusion的API接口对接功能

### ISSUE THREAD

**Issue by Pythonpa** [l15y/wenda#9]
辛苦作者，建议后续增加接入Stable Diffusion的API接口对接功能，类似Text generation webUI这个项目

**Comment by l15y** [comment]
没明白，直接调用sd生成图片？

**Comment by Pythonpa** [comment]
> 没明白，直接调用sd生成图片？

是的，SD支持接口调用，这样就把AI生成文字和图片2大实用功能打通了。

**Comment by l15y** [comment]
如果你能实现glm模型生成正确的sd prompt，可以加这个功能

**Comment by jcs130** [comment]
> 如果你能实现glm模型生成正确的sd prompt，可以加这个功能
> > 没明白，直接调用sd生成图片？
> 
> 是的，SD支持接口调用，这样就把AI生成文字和图片2大实用功能打通了。
还真有个项目是这样的：
https://github.com/visual-openllm/visual-openllm
