### ISSUE TITLE
icetk与protobuf不兼容

### ISSUE THREAD

**Issue by Yamol** [l15y/wenda#96]
**Describe the bug**
ChatGLM 需要安装最新的 protobuf，也就是 4.22.1；
wenda 需要安装 icetk，但是要求 protobuf 的版本 < 3.19；
所以要运行 ChatGLM 就不能运行 wenda，要配置wenda 就不能用 ChatGLM。

**Desktop (please complete the following information):**
nvcc -V: Build cuda_12.1.r12.1/compiler.32415258_0
nvidia-smi: Driver Version: 530.30.02    CUDA Version: 12.1
torch.__version__: '2.0.0+cu118'
torch.version.cuda: '11.8'

**Comment by Yamol** [comment]
而且 ChatGLM 的 transformers==4.27.1，wenda 的是 transformers==4.26.1

**Comment by l15y** [comment]
可以忽略这个报错
