### ISSUE TITLE
Bing模式中是否能提供参考链接

### ISSUE THREAD

**Issue by wangfh5** [l15y/wenda#97]
为了判断是模型自己说的还是参考了网页内容, 可以像本地知识库模式附上参考文件一样, 附上参考链接. 当然, 能像newbing一样将文本渲染为超链接就更强了.

**Comment by wangfh5** [comment]
如果有参考链接和参考文献进行区分的话, 是否可以同时进行本地知识库和联网知识库的检索?

**Comment by wangfh5** [comment]
我想说的是Ai的回复框中加上

来源:
链接1
链接2
链接3

文档中说的好像是知识库那个标签页里面你可以用测试来查看参考链接

**Comment by l15y** [comment]
有，setting.bat
