### ISSUE TITLE
WebUI: 拉到最上面顶部标签栏才会出现

### ISSUE THREAD

**Issue by wangfh5** [l15y/wenda#99]
进入webUI之后, 最上面的标签栏只有将进度条拉到最上面才会显示, 不方便开关历史, 知识库.
![image](https://user-images.githubusercontent.com/51868839/231199768-051a3020-b310-4231-838a-70967c0b6a92.png)
![image](https://user-images.githubusercontent.com/51868839/231199775-15d095e2-a61d-4cdc-8ba7-3e5f770db8ed.png)

**Comment by l15y** [comment]
修了
